all:
	arm-linux-gnueabihf-gcc libcaptest.c -lcap -o setnetcap
	arm-linux-gnueabihf-gcc setcat.c -lcap -o setcap
	arm-linux-gnueabihf-gcc getcap.c -lcap -o getcap
	arm-linux-gnueabihf-gcc capsettest.c -lcap -o captest