all:
	arm-linux-gnueabihf-$(CXX) -Wall singleton_main.cpp DataProcessMgr.cpp sharemem.cpp -o timetest -lpthread
	$(CXX) -Wall singleton_main2.cpp DataProcessMgr.cpp sharemem.cpp -o timetest2 -lpthread
